# Docker Compose for Impactor-2025 Production Environment
version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
      - NASA_API_KEY=${NASA_API_KEY}
      - ENVIRONMENT=production
    networks:
      - impactor-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Frontend Web Service (Production Build)
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
    networks:
      - impactor-network
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # Redis for caching
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - impactor-network
    restart: always
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - impactor-network
    depends_on:
      - frontend
      - backend
    restart: always

networks:
  impactor-network:
    driver: bridge
    name: impactor-network-prod

volumes:
  redis_data:
    driver: local